# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-31 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='roles',
            field=models.ManyToManyField(blank=True, to='app01.Role', verbose_name='所属角色'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='ut',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app01.UserType', verbose_name='用户类型'),
        ),
    ]
